# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arti-Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arti-Chat
  pod 'OAuthSwift', '~> 1.1.0'

  target 'Arti-ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Arti-ChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
